# EDA, Tuberculosis in the United States

In [ ]:
# Acknowledgments (tutorial, code(modified)): Lisa Yan

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive/')

# Tuberculosis in the United States

What can we say about the presence of Tuberculosis in the United States?

Let's look at the data included in the [original CDC article](https://www.cdc.gov/mmwr/volumes/71/wr/mm7112a1.htm?s_cid=mm7112a1_w#T1_down) published in 2021.

<br>

---

# CSV and Nice Field Names
Please use the CSV file `cdc_tuberculosis.csv`.

We can then explore the CSV (which is a text file, and does not contain binary-encoded data) in many ways:
1. Using a the jupyter lab explorer tool look at the data
2. Opening the CSV directly in DataHub (read-only), Excel, Google Sheets, etc.
3. The Python file object
4. pandas, using `pd.read_csv()`

In [4]:
df_tb = pd.read_csv("./cdc_tuberculosis.csv")
df_tb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       53 non-null     object
 1   No. of TB cases  53 non-null     object
 2   Unnamed: 2       53 non-null     object
 3   Unnamed: 3       53 non-null     object
 4   TB incidence     53 non-null     float64
 5   Unnamed: 5       53 non-null     float64
 6   Unnamed: 6       53 non-null     float64
dtypes: float64(3), object(4)
memory usage: 3.0+ KB

<br>


---

## Play with the data in the Jupyter Lab Explorer
1, 2. Let's start with the first two so we really solidify the idea of a CSV as **rectangular data (i.e., tabular data) stored as comma-separated values**.

<br>

---

## Play with the data in python

3. Next, let's try using the Python file object. Let's check out the first four lines:

In [2]:
#!ls
#!ls "/content/drive/My Drive/Colab Notebooks/data"

# with open("/content/drive/My Drive/Colab Notebooks/data/cdc_tuberculosis.csv", "r") as f:
with open("./cdc_tuberculosis.csv", "r") as f:
    for i, row in enumerate(f):
        print(row)
        if i >= 3: break

,No. of TB cases,,,TB incidence,,

U.S. jurisdiction,2019,2020,2021,2019,2020,2021

Total,"8,900","7,173","7,860",2.71,2.16,2.37

Alabama,87,72,92,1.77,1.43,1.83

Whoa, why are there blank lines interspaced between the lines of the CSV?

In [5]:
with open("./cdc_tuberculosis.csv", "r") as f:
    for i, row in enumerate(f):
        print(repr(row)) # print raw strings
        if i >= 3: break

',No. of TB cases,,,TB incidence,,\n'
'U.S. jurisdiction,2019,2020,2021,2019,2020,2021\n'
'Total,"8,900","7,173","7,860",2.71,2.16,2.37\n'
'Alabama,87,72,92,1.77,1.43,1.83\n'

Wait, what's up with the "Unnamed" column names? And the first row, for that matter?

Congratulations -- you're ready to wrangle your data. Because of how things are stored, we'll need to clean the data a bit to name our columns better.

A reasonable first step is to identify the row with the right header. The `pd.read_csv()` function ([documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)) has the convenient `header` parameter.

You could also try:
1. Shift+Tab while your cursor is in the function call parenthesis.
1. `Cmd+i` or `Ctrl+i` to get contextual help.

In [6]:
tb_df = pd.read_csv("./cdc_tuberculosis.csv", header=1) # row index
tb_df

       U.S. jurisdiction   2019   2020   2021  2019.1  2020.1  2021.1
0                  Total  8,900  7,173  7,860    2.71    2.16    2.37
1                Alabama     87     72     92    1.77    1.43    1.83
2                 Alaska     58     58     58    7.91    7.92    7.92
3                Arizona    183    136    129    2.51    1.89    1.77
4               Arkansas     64     59     69    2.12    1.96    2.28
5             California  2,111  1,706  1,750    5.35    4.32    4.46
6               Colorado     66     52     58    1.15    0.90    1.00
7            Connecticut     67     54     54    1.88    1.50    1.50
8               Delaware     18     17     43    1.84    1.71    4.29
9   District of Columbia     24     19     19    3.39    2.75    2.84
10               Florida    558    412    499    2.60    1.91    2.29
11               Georgia    302    221    228    2.84    2.06    2.11
12                Hawaii     99     92    106    6.99    6.34    7.35
13                 Idaho      7      8      4    0.39    0.43    0.21
14              Illinois    326    216    255    2.57    1.69    2.01
15               Indiana    108     92    127    1.60    1.36    1.87
16                  Iowa     52     39     49    1.65    1.22    1.53
17                Kansas     37     37     43    1.27    1.26    1.47
18              Kentucky     66     67     57    1.48    1.49    1.26
19             Louisiana     88     99     86    1.89    2.13    1.86
20                 Maine     18     17     14    1.34    1.25    1.02
21              Maryland    209    148    192    3.45    2.40    3.11
22         Massachusetts    178    142    151    2.58    2.02    2.16
23              Michigan    131    101    136    1.31    1.00    1.35
24             Minnesota    148    117    134    2.62    2.05    2.35
25           Mississippi     58     41     45    1.95    1.39    1.53
26              Missouri     70     79     77    1.14    1.28    1.25
27               Montana      2      4      3    0.19    0.37    0.27
28              Nebraska     17     33     22    0.88    1.68    1.12
29                Nevada     53     57     61    1.71    1.83    1.94
30         New Hampshire      6     12     12    0.44    0.87    0.86
31            New Jersey    310    245    279    3.49    2.64    3.01
32            New Mexico     41     29     24    1.95    1.37    1.13
33              New York    746    605    681    3.83    3.00    3.43
34        North Carolina    185    159    178    1.76    1.52    1.69
35          North Dakota     18     10     15    2.36    1.28    1.94
36                  Ohio    150    130    149    1.28    1.10    1.26
37              Oklahoma     73     67     69    1.84    1.69    1.73
38                Oregon     70     67     78    1.66    1.58    1.84
39          Pennsylvania    199    156    166    1.55    1.20    1.28
40          Rhode Island     14      7     17    1.32    0.64    1.55
41        South Carolina     80     67     88    1.55    1.31    1.70
42          South Dakota     16     16     12    1.80    1.80    1.34
43             Tennessee    129    113     85    1.89    1.63    1.22
44                 Texas  1,154    883    991    3.98    3.02    3.36
45                  Utah     27     29     17    0.84    0.88    0.51
46               Vermont      4      3      2    0.64    0.47    0.31
47              Virginia    191    169    161    2.23    1.96    1.86
48            Washington    221    163    199    2.90    2.11    2.57
49         West Virginia      9     13      7    0.50    0.73    0.39
50             Wisconsin     51     35     66    0.88    0.59    1.12
51               Wyoming      1      0      3    0.17    0.00    0.52

<br><br>
Wait...but now we can't differentiate betwen the "Number of TB cases" and "TB incidence" year columns. pandas has tried to make our lives easier by automatically adding ".1" to the latter columns, but this doesn't help us as humans understand the data.

We can do this manually with `df.rename()` ([documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html?highlight=rename#pandas.DataFrame.rename)):

In [7]:
rename_dict = {'2019': 'TB cases 2019',
               '2020': 'TB cases 2020',
               '2021': 'TB cases 2021',
               '2019.1': 'TB incidence 2019',
               '2020.1': 'TB incidence 2020',
               '2021.1': 'TB incidence 2021'}
tb_df = tb_df.rename(columns=rename_dict)
tb_df

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
0,Total,"8,900","7,173","7,860",2.71,2.16,2.37
1,Alabama,87,72,92,1.77,1.43,1.83
2,Alaska,58,58,58,7.91,7.92,7.92
3,Arizona,183,136,129,2.51,1.89,1.77
4,Arkansas,64,59,69,2.12,1.96,2.28
5,California,"2,111","1,706","1,750",5.35,4.32,4.46
6,Colorado,66,52,58,1.15,0.90,1.00
7,Connecticut,67,54,54,1.88,1.50,1.50
8,Delaware,18,17,43,1.84,1.71,4.29
9,District of Columbia,24,19,19,3.39,2.75,2.84
10,Florida,558,412,499,2.60,1.91,2.29
11,Georgia,302,221,228,2.84,2.06,2.11
12,Hawaii,99,92,106,6.99,6.34,7.35
13,Idaho,7,8,4,0.39,0.43,0.21
14,Illinois,326,216,255,2.57,1.69,2.01
15,Indiana,108,92,127,1.60,1.36,1.87
16,Iowa,52,39,49,1.65,1.22,1.53
17,Kansas,37,37,43,1.27,1.26,1.47
18,Kentucky,66,67,57,1.48,1.49,1.26
19,Louisiana,88,99,86,1.89,2.13,1.86
20,Maine,18,17,14,1.34,1.25,1.02
21,Maryland,209,148,192,3.45,2.40,3.11
22,Massachusetts,178,142,151,2.58,2.02,2.16
23,Michigan,131,101,136,1.31,1.00,1.35
24,Minnesota,148,117,134,2.62,2.05,2.35
25,Mississippi,58,41,45,1.95,1.39,1.53
26,Missouri,70,79,77,1.14,1.28,1.25
27,Montana,2,4,3,0.19,0.37,0.27
28,Nebraska,17,33,22,0.88,1.68,1.12
29,Nevada,53,57,61,1.71,1.83,1.94
30,New Hampshire,6,12,12,0.44,0.87,0.86
31,New Jersey,310,245,279,3.49,2.64,3.01
32,New Mexico,41,29,24,1.95,1.37,1.13
33,New York,746,605,681,3.83,3.00,3.43
34,North Carolina,185,159,178,1.76,1.52,1.69
35,North Dakota,18,10,15,2.36,1.28,1.94
36,Ohio,150,130,149,1.28,1.10,1.26
37,Oklahoma,73,67,69,1.84,1.69,1.73
38,Oregon,70,67,78,1.66,1.58,1.84
39,Pennsylvania,199,156,166,1.55,1.20,1.28
40,Rhode Island,14,7,17,1.32,0.64,1.55
41,South Carolina,80,67,88,1.55,1.31,1.70
42,South Dakota,16,16,12,1.80,1.80,1.34
43,Tennessee,129,113,85,1.89,1.63,1.22
44,Texas,"1,154",883,991,3.98,3.02,3.36
45,Utah,27,29,17,0.84,0.88,0.51
46,Vermont,4,3,2,0.64,0.47,0.31
47,Virginia,191,169,161,2.23,1.96,1.86
48,Washington,221,163,199,2.90,2.11,2.57
49,West Virginia,9,13,7,0.50,0.73,0.39
50,Wisconsin,51,35,66,0.88,0.59,1.12
51,Wyoming,1,0,3,0.17,0.00,0.52

<br/><br/>

---

# Record Granularity

You might already be wondering: What's up with that first record?

Row 0 is what we call a **rollup record**, or summary record. It's often useful when displaying tables to humans. The **granularity** of record 0 (Totals) vs the rest of the records (States) is different.

In [8]:
tb_df.head()

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
0,Total,"8,900","7,173","7,860",2.71,2.16,2.37
1,Alabama,87,72,92,1.77,1.43,1.83
2,Alaska,58,58,58,7.91,7.92,7.92
3,Arizona,183,136,129,2.51,1.89,1.77
4,Arkansas,64,59,69,2.12,1.96,2.28

<br/>

Okay, EDA step two. How was the rollup record aggregated?

Let's check if Total TB cases is the sum of all state TB cases. We can drop it and try to sum up all the remaining rows.

In [9]:
tb_df.drop(0)

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
1,Alabama,87,72,92,1.77,1.43,1.83
2,Alaska,58,58,58,7.91,7.92,7.92
3,Arizona,183,136,129,2.51,1.89,1.77
4,Arkansas,64,59,69,2.12,1.96,2.28
5,California,"2,111","1,706","1,750",5.35,4.32,4.46
6,Colorado,66,52,58,1.15,0.90,1.00
7,Connecticut,67,54,54,1.88,1.50,1.50
8,Delaware,18,17,43,1.84,1.71,4.29
9,District of Columbia,24,19,19,3.39,2.75,2.84
10,Florida,558,412,499,2.60,1.91,2.29
11,Georgia,302,221,228,2.84,2.06,2.11
12,Hawaii,99,92,106,6.99,6.34,7.35
13,Idaho,7,8,4,0.39,0.43,0.21
14,Illinois,326,216,255,2.57,1.69,2.01
15,Indiana,108,92,127,1.60,1.36,1.87
16,Iowa,52,39,49,1.65,1.22,1.53
17,Kansas,37,37,43,1.27,1.26,1.47
18,Kentucky,66,67,57,1.48,1.49,1.26
19,Louisiana,88,99,86,1.89,2.13,1.86
20,Maine,18,17,14,1.34,1.25,1.02
21,Maryland,209,148,192,3.45,2.40,3.11
22,Massachusetts,178,142,151,2.58,2.02,2.16
23,Michigan,131,101,136,1.31,1.00,1.35
24,Minnesota,148,117,134,2.62,2.05,2.35
25,Mississippi,58,41,45,1.95,1.39,1.53
26,Missouri,70,79,77,1.14,1.28,1.25
27,Montana,2,4,3,0.19,0.37,0.27
28,Nebraska,17,33,22,0.88,1.68,1.12
29,Nevada,53,57,61,1.71,1.83,1.94
30,New Hampshire,6,12,12,0.44,0.87,0.86
31,New Jersey,310,245,279,3.49,2.64,3.01
32,New Mexico,41,29,24,1.95,1.37,1.13
33,New York,746,605,681,3.83,3.00,3.43
34,North Carolina,185,159,178,1.76,1.52,1.69
35,North Dakota,18,10,15,2.36,1.28,1.94
36,Ohio,150,130,149,1.28,1.10,1.26
37,Oklahoma,73,67,69,1.84,1.69,1.73
38,Oregon,70,67,78,1.66,1.58,1.84
39,Pennsylvania,199,156,166,1.55,1.20,1.28
40,Rhode Island,14,7,17,1.32,0.64,1.55
41,South Carolina,80,67,88,1.55,1.31,1.70
42,South Dakota,16,16,12,1.80,1.80,1.34
43,Tennessee,129,113,85,1.89,1.63,1.22
44,Texas,"1,154",883,991,3.98,3.02,3.36
45,Utah,27,29,17,0.84,0.88,0.51
46,Vermont,4,3,2,0.64,0.47,0.31
47,Virginia,191,169,161,2.23,1.96,1.86
48,Washington,221,163,199,2.90,2.11,2.57
49,West Virginia,9,13,7,0.50,0.73,0.39
50,Wisconsin,51,35,66,0.88,0.59,1.12
51,Wyoming,1,0,3,0.17,0.00,0.52

In [ ]:
tb_df.drop(0).sum()

<br/>

Whoa, what's going on? Check out the column types:

In [10]:
tb_df.dtypes

U.S. jurisdiction     object
TB cases 2019         object
TB cases 2020         object
TB cases 2021         object
TB incidence 2019    float64
TB incidence 2020    float64
TB incidence 2021    float64
dtype: object

<br/>

Looks like those commas are causing all TB cases to be read as the `object` datatype, or **storage type** (close to the Python string datatype), so pandas is concatenating strings instead of adding integers.

<br/>

Fortunately `read_csv` also has a `thousands` parameter (for what it's worth, I didn't know this beforehand--I [googled](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) this):

In [12]:
# improve readability: chaining method calls with outer parentheses/line breaks
tb_df = (
    pd.read_csv("./cdc_tuberculosis.csv", header=1, thousands=',')
    .rename(columns=rename_dict)
)
tb_df

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
0,Total,8900,7173,7860,2.71,2.16,2.37
1,Alabama,87,72,92,1.77,1.43,1.83
2,Alaska,58,58,58,7.91,7.92,7.92
3,Arizona,183,136,129,2.51,1.89,1.77
4,Arkansas,64,59,69,2.12,1.96,2.28
5,California,2111,1706,1750,5.35,4.32,4.46
6,Colorado,66,52,58,1.15,0.90,1.00
7,Connecticut,67,54,54,1.88,1.50,1.50
8,Delaware,18,17,43,1.84,1.71,4.29
9,District of Columbia,24,19,19,3.39,2.75,2.84
10,Florida,558,412,499,2.60,1.91,2.29
11,Georgia,302,221,228,2.84,2.06,2.11
12,Hawaii,99,92,106,6.99,6.34,7.35
13,Idaho,7,8,4,0.39,0.43,0.21
14,Illinois,326,216,255,2.57,1.69,2.01
15,Indiana,108,92,127,1.60,1.36,1.87
16,Iowa,52,39,49,1.65,1.22,1.53
17,Kansas,37,37,43,1.27,1.26,1.47
18,Kentucky,66,67,57,1.48,1.49,1.26
19,Louisiana,88,99,86,1.89,2.13,1.86
20,Maine,18,17,14,1.34,1.25,1.02
21,Maryland,209,148,192,3.45,2.40,3.11
22,Massachusetts,178,142,151,2.58,2.02,2.16
23,Michigan,131,101,136,1.31,1.00,1.35
24,Minnesota,148,117,134,2.62,2.05,2.35
25,Mississippi,58,41,45,1.95,1.39,1.53
26,Missouri,70,79,77,1.14,1.28,1.25
27,Montana,2,4,3,0.19,0.37,0.27
28,Nebraska,17,33,22,0.88,1.68,1.12
29,Nevada,53,57,61,1.71,1.83,1.94
30,New Hampshire,6,12,12,0.44,0.87,0.86
31,New Jersey,310,245,279,3.49,2.64,3.01
32,New Mexico,41,29,24,1.95,1.37,1.13
33,New York,746,605,681,3.83,3.00,3.43
34,North Carolina,185,159,178,1.76,1.52,1.69
35,North Dakota,18,10,15,2.36,1.28,1.94
36,Ohio,150,130,149,1.28,1.10,1.26
37,Oklahoma,73,67,69,1.84,1.69,1.73
38,Oregon,70,67,78,1.66,1.58,1.84
39,Pennsylvania,199,156,166,1.55,1.20,1.28
40,Rhode Island,14,7,17,1.32,0.64,1.55
41,South Carolina,80,67,88,1.55,1.31,1.70
42,South Dakota,16,16,12,1.80,1.80,1.34
43,Tennessee,129,113,85,1.89,1.63,1.22
44,Texas,1154,883,991,3.98,3.02,3.36
45,Utah,27,29,17,0.84,0.88,0.51
46,Vermont,4,3,2,0.64,0.47,0.31
47,Virginia,191,169,161,2.23,1.96,1.86
48,Washington,221,163,199,2.90,2.11,2.57
49,West Virginia,9,13,7,0.50,0.73,0.39
50,Wisconsin,51,35,66,0.88,0.59,1.12
51,Wyoming,1,0,3,0.17,0.00,0.52

In [ ]:
tb_df.drop(0).sum()

In [13]:
tb_df.head(1)

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
0,Total,8900,7173,7860,2.71,2.16,2.37

The Total TB cases look right. Phew!

(We'll leave it to your own EDA to figure out how the TB incidence "Totals" were aggregated.)

In order to compute incidence we are going to need more data: **population information**!!

<br/><br/>

---

# Gather Census Data

U.S. Census population estimates [source](https://www.census.gov/data/tables/time-series/demo/popest/2010s-state-total.html) (2019), [source](https://www.census.gov/data/tables/time-series/demo/popest/2020s-state-total.html) (2020-2021).

Running the below cells cleans the data. We encourage you to closely explore the CSV and study these lines after lecture...

There are a few new methods here:
* `df.convert_dtypes()` ([documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.convert_dtypes.html)) conveniently converts all float dtypes into ints and is out of scope for the class.
* `df.drop_na()` ([documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html)) will be explained in more detail next time.

In [14]:
census_2010s_df = pd.read_csv("./nst-est2019-01.csv", header=3, thousands=",")
census_2010s_df

,Unnamed: 0,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,United States,308745538.0,308758105.0,309321666.0,311556874.0,313830990.0,315993715.0,318301008.0,320635163.0,322941311.0,324985539.0,326687501.0,328239523.0
1,Northeast,55317240.0,55318443.0,55380134.0,55604223.0,55775216.0,55901806.0,56006011.0,56034684.0,56042330.0,56059240.0,56046620.0,55982803.0
2,Midwest,66927001.0,66929725.0,66974416.0,67157800.0,67336743.0,67560379.0,67745167.0,67860583.0,67987540.0,68126781.0,68236628.0,68329004.0
3,South,114555744.0,114563030.0,114866680.0,116006522.0,117241208.0,118364400.0,119624037.0,120997341.0,122351760.0,123542189.0,124569433.0,125580448.0
4,West,71945553.0,71946907.0,72100436.0,72788329.0,73477823.0,74167130.0,74925793.0,75742555.0,76559681.0,77257329.0,77834820.0,78347268.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Note: The estimates are based on the 2010 Cens...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Suggested Citation:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Table 1. Annual Estimates of the Resident Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,"Source: U.S. Census Bureau, Population Division",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Release Date: December 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Do some basic data cleaning

In [15]:
census_2010s_df = (
    census_2010s_df
    .rename(columns={"Unnamed: 0": "Geographic Area"})
    .drop(columns=["Census", "Estimates Base"])
    .convert_dtypes() # "smart" converting of columns to int, use at your own risk
    .dropna()  # we'll introduce this very soon
)
census_2010s_df

,Geographic Area,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,United States,309321666,311556874,313830990,315993715,318301008,320635163,322941311,324985539,326687501,328239523
1,Northeast,55380134,55604223,55775216,55901806,56006011,56034684,56042330,56059240,56046620,55982803
2,Midwest,66974416,67157800,67336743,67560379,67745167,67860583,67987540,68126781,68236628,68329004
3,South,114866680,116006522,117241208,118364400,119624037,120997341,122351760,123542189,124569433,125580448
4,West,72100436,72788329,73477823,74167130,74925793,75742555,76559681,77257329,77834820,78347268
5,.Alabama,4785437,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185
6,.Alaska,713910,722128,730443,737068,736283,737498,741456,739700,735139,731545
7,.Arizona,6407172,6472643,6554978,6632764,6730413,6829676,6941072,7044008,7158024,7278717
8,.Arkansas,2921964,2940667,2952164,2959400,2967392,2978048,2989918,3001345,3009733,3017804
9,.California,37319502,37638369,37948800,38260787,38596972,38918045,39167117,39358497,39461588,39512223
10,.Colorado,5047349,5121108,5192647,5269035,5350101,5450623,5539215,5611885,5691287,5758736
11,.Connecticut,3579114,3588283,3594547,3594841,3594524,3587122,3578141,3573297,3571520,3565287
12,.Delaware,899593,907381,915179,923576,932487,941252,948921,956823,965479,973764
13,.District of Columbia,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
14,.Florida,18845537,19053237,19297822,19545621,19845911,20209042,20613477,20963613,21244317,21477737
15,.Georgia,9711881,9802431,9901430,9972479,10067278,10178447,10301890,10410330,10511131,10617423
16,.Hawaii,1363963,1379329,1394804,1408243,1414538,1422052,1427559,1424393,1420593,1415872
17,.Idaho,1570746,1583910,1595324,1611206,1631112,1651059,1682380,1717715,1750536,1787065
18,.Illinois,12840503,12867454,12882510,12895129,12884493,12858913,12820527,12778828,12723071,12671821
19,.Indiana,6490432,6516528,6537703,6568713,6593644,6608422,6634304,6658078,6695497,6732219
20,.Iowa,3050745,3066336,3076190,3092997,3109350,3120960,3131371,3141550,3148618,3155070
21,.Kansas,2858190,2869225,2885257,2893212,2900475,2909011,2910844,2908718,2911359,2913314
22,.Kentucky,4348181,4369821,4386346,4404659,4414349,4425976,4438182,4452268,4461153,4467673
23,.Louisiana,4544532,4575625,4600972,4624527,4644013,4664628,4678135,4670560,4659690,4648794
24,.Maine,1327629,1328284,1327729,1328009,1330513,1328262,1331317,1334612,1339057,1344212
25,.Maryland,5788645,5839419,5886992,5923188,5957283,5985562,6003323,6023868,6035802,6045680
26,.Massachusetts,6566307,6613583,6663005,6713315,6762596,6794228,6823608,6859789,6882635,6892503
27,.Michigan,9877510,9882412,9897145,9913065,9929848,9931715,9950571,9973114,9984072,9986857
28,.Minnesota,5310828,5346143,5376643,5413479,5451079,5482032,5522744,5566230,5606249,5639632
29,.Mississippi,2970548,2978731,2983816,2988711,2990468,2988471,2987938,2988510,2981020,2976149
30,.Missouri,5995974,6010275,6024367,6040715,6056202,6071732,6087135,6106670,6121623,6137428
31,.Montana,990697,997316,1003783,1013569,1021869,1030475,1040859,1052482,1060665,1068778
32,.Nebraska,1829542,1840672,1853303,1865279,1879321,1891277,1905616,1915947,1925614,1934408
33,.Nevada,2702405,2712730,2743996,2775970,2817628,2866939,2917563,2969905,3027341,3080156
34,.New Hampshire,1316762,1320202,1324232,1326622,1333341,1336350,1342307,1348787,1353465,1359711
35,.New Jersey,8799446,8828117,8844942,8856972,8864525,8867949,8870827,8885525,8886025,8882190
36,.New Mexico,2064552,2080450,2087309,2092273,2089568,2089291,2091630,2091784,2092741,2096829
37,.New York,19399878,19499241,19572932,19624447,19651049,19654666,19633428,19589572,19530351,19453561
38,.North Carolina,9574323,9657592,9749476,9843336,9932887,10031646,10154788,10268233,10381615,10488084
39,.North Dakota,674715,685225,701176,722036,737401,754066,754434,754942,758080,762062
40,.Ohio,11539336,11544663,11548923,11576684,11602700,11617527,11634370,11659650,11676341,11689100
41,.Oklahoma,3759944,3788379,3818814,3853214,3878187,3909500,3926331,3931316,3940235,3956971
42,.Oregon,3837491,3872036,3899001,3922468,3963244,4015792,4089976,4143625,4181886,4217737
43,.Pennsylvania,12711160,12745815,12767118,12776309,12788313,12784826,12782275,12787641,12800922,12801989
44,.Rhode Island,1053959,1053649,1054621,1055081,1055936,1056065,1056770,1055673,1058287,1059361
45,.South Carolina,4635649,4671994,4717354,4764080,4823617,4891938,4957968,5021268,5084156,5148714
46,.South Dakota,816166,823579,833566,842316,849129,853988,862996,872868,878698,884659
47,.Tennessee,6355311,6399291,6453898,6494340,6541223,6591170,6646010,6708799,6771631,6829174
48,.Texas,25241971,25645629,26084481,26480266,26964333,27470056,27914410,28295273,28628666,28995881
49,.Utah,2775332,2814384,2853375,2897640,2936879,2981835,3041868,3101042,3153550,3205958
50,.Vermont,625879,627049,626090,626210,625214,625216,623657,624344,624358,623989
51,.Virginia,8023699,8101155,8185080,8252427,8310993,8361808,8410106,8463587,8501286,8535519
52,.Washington,6742830,6826627,6897058,6963985,7054655,7163657,7294771,7423362,7523869,7614893
53,.West Virginia,1854239,1856301,1856872,1853914,1849489,1842050,1831023,1817004,1804291,1792147
54,.Wisconsin,5690475,5705288,5719960,5736754,5751525,5760940,5772628,5790186,5807406,5822434
55,.Wyoming,564487,567299,576305,582122,582531,585613,584215,578931,577601,578759
57,Puerto Rico,3721525,3678732,3634488,3593077,3534874,3473232,3406672,3325286,3193354,3193694

What is the granularity of each row in this table.

Notice there is a `'.'` at the beginning of all the states.  We need to remove that.

In [16]:
census_2010s_df['Geographic Area'] = census_2010s_df['Geographic Area'].str.strip('.')
census_2010s_df

,Geographic Area,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,United States,309321666,311556874,313830990,315993715,318301008,320635163,322941311,324985539,326687501,328239523
1,Northeast,55380134,55604223,55775216,55901806,56006011,56034684,56042330,56059240,56046620,55982803
2,Midwest,66974416,67157800,67336743,67560379,67745167,67860583,67987540,68126781,68236628,68329004
3,South,114866680,116006522,117241208,118364400,119624037,120997341,122351760,123542189,124569433,125580448
4,West,72100436,72788329,73477823,74167130,74925793,75742555,76559681,77257329,77834820,78347268
5,Alabama,4785437,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185
6,Alaska,713910,722128,730443,737068,736283,737498,741456,739700,735139,731545
7,Arizona,6407172,6472643,6554978,6632764,6730413,6829676,6941072,7044008,7158024,7278717
8,Arkansas,2921964,2940667,2952164,2959400,2967392,2978048,2989918,3001345,3009733,3017804
9,California,37319502,37638369,37948800,38260787,38596972,38918045,39167117,39358497,39461588,39512223
10,Colorado,5047349,5121108,5192647,5269035,5350101,5450623,5539215,5611885,5691287,5758736
11,Connecticut,3579114,3588283,3594547,3594841,3594524,3587122,3578141,3573297,3571520,3565287
12,Delaware,899593,907381,915179,923576,932487,941252,948921,956823,965479,973764
13,District of Columbia,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
14,Florida,18845537,19053237,19297822,19545621,19845911,20209042,20613477,20963613,21244317,21477737
15,Georgia,9711881,9802431,9901430,9972479,10067278,10178447,10301890,10410330,10511131,10617423
16,Hawaii,1363963,1379329,1394804,1408243,1414538,1422052,1427559,1424393,1420593,1415872
17,Idaho,1570746,1583910,1595324,1611206,1631112,1651059,1682380,1717715,1750536,1787065
18,Illinois,12840503,12867454,12882510,12895129,12884493,12858913,12820527,12778828,12723071,12671821
19,Indiana,6490432,6516528,6537703,6568713,6593644,6608422,6634304,6658078,6695497,6732219
20,Iowa,3050745,3066336,3076190,3092997,3109350,3120960,3131371,3141550,3148618,3155070
21,Kansas,2858190,2869225,2885257,2893212,2900475,2909011,2910844,2908718,2911359,2913314
22,Kentucky,4348181,4369821,4386346,4404659,4414349,4425976,4438182,4452268,4461153,4467673
23,Louisiana,4544532,4575625,4600972,4624527,4644013,4664628,4678135,4670560,4659690,4648794
24,Maine,1327629,1328284,1327729,1328009,1330513,1328262,1331317,1334612,1339057,1344212
25,Maryland,5788645,5839419,5886992,5923188,5957283,5985562,6003323,6023868,6035802,6045680
26,Massachusetts,6566307,6613583,6663005,6713315,6762596,6794228,6823608,6859789,6882635,6892503
27,Michigan,9877510,9882412,9897145,9913065,9929848,9931715,9950571,9973114,9984072,9986857
28,Minnesota,5310828,5346143,5376643,5413479,5451079,5482032,5522744,5566230,5606249,5639632
29,Mississippi,2970548,2978731,2983816,2988711,2990468,2988471,2987938,2988510,2981020,2976149
30,Missouri,5995974,6010275,6024367,6040715,6056202,6071732,6087135,6106670,6121623,6137428
31,Montana,990697,997316,1003783,1013569,1021869,1030475,1040859,1052482,1060665,1068778
32,Nebraska,1829542,1840672,1853303,1865279,1879321,1891277,1905616,1915947,1925614,1934408
33,Nevada,2702405,2712730,2743996,2775970,2817628,2866939,2917563,2969905,3027341,3080156
34,New Hampshire,1316762,1320202,1324232,1326622,1333341,1336350,1342307,1348787,1353465,1359711
35,New Jersey,8799446,8828117,8844942,8856972,8864525,8867949,8870827,8885525,8886025,8882190
36,New Mexico,2064552,2080450,2087309,2092273,2089568,2089291,2091630,2091784,2092741,2096829
37,New York,19399878,19499241,19572932,19624447,19651049,19654666,19633428,19589572,19530351,19453561
38,North Carolina,9574323,9657592,9749476,9843336,9932887,10031646,10154788,10268233,10381615,10488084
39,North Dakota,674715,685225,701176,722036,737401,754066,754434,754942,758080,762062
40,Ohio,11539336,11544663,11548923,11576684,11602700,11617527,11634370,11659650,11676341,11689100
41,Oklahoma,3759944,3788379,3818814,3853214,3878187,3909500,3926331,3931316,3940235,3956971
42,Oregon,3837491,3872036,3899001,3922468,3963244,4015792,4089976,4143625,4181886,4217737
43,Pennsylvania,12711160,12745815,12767118,12776309,12788313,12784826,12782275,12787641,12800922,12801989
44,Rhode Island,1053959,1053649,1054621,1055081,1055936,1056065,1056770,1055673,1058287,1059361
45,South Carolina,4635649,4671994,4717354,4764080,4823617,4891938,4957968,5021268,5084156,5148714
46,South Dakota,816166,823579,833566,842316,849129,853988,862996,872868,878698,884659
47,Tennessee,6355311,6399291,6453898,6494340,6541223,6591170,6646010,6708799,6771631,6829174
48,Texas,25241971,25645629,26084481,26480266,26964333,27470056,27914410,28295273,28628666,28995881
49,Utah,2775332,2814384,2853375,2897640,2936879,2981835,3041868,3101042,3153550,3205958
50,Vermont,625879,627049,626090,626210,625214,625216,623657,624344,624358,623989
51,Virginia,8023699,8101155,8185080,8252427,8310993,8361808,8410106,8463587,8501286,8535519
52,Washington,6742830,6826627,6897058,6963985,7054655,7163657,7294771,7423362,7523869,7614893
53,West Virginia,1854239,1856301,1856872,1853914,1849489,1842050,1831023,1817004,1804291,1792147
54,Wisconsin,5690475,5705288,5719960,5736754,5751525,5760940,5772628,5790186,5807406,5822434
55,Wyoming,564487,567299,576305,582122,582531,585613,584215,578931,577601,578759
57,Puerto Rico,3721525,3678732,3634488,3593077,3534874,3473232,3406672,3325286,3193354,3193694

## Loading the 2020s data
The 2020s data is in a separate file so we will repeate the same data cleaning process.

In [17]:
# census 2020s data
census_2020s_df = pd.read_csv("./NST-EST2022-POP.csv", header=3, thousands=",")
census_2020s_df = (
    census_2020s_df
    .drop(columns=["Unnamed: 1"])
    .rename(columns={"Unnamed: 0": "Geographic Area"})
    .convert_dtypes()
    .dropna()
)
census_2020s_df['Geographic Area'] = census_2020s_df['Geographic Area'].str.strip('.')
census_2020s_df

         Geographic Area       2020       2021       2022
0          United States  331511512  332031554  333287557
1              Northeast   57448898   57259257   57040406
2                Midwest   68961043   68836505   68787595
3                  South  126450613  127346029  128716192
4                   West   78650958   78589763   78743364
5                Alabama    5031362    5049846    5074296
6                 Alaska     732923     734182     733583
7                Arizona    7179943    7264877    7359197
8               Arkansas    3014195    3028122    3045637
9             California   39501653   39142991   39029342
10              Colorado    5784865    5811297    5839926
11           Connecticut    3597362    3623355    3626205
12              Delaware     992114    1004807    1018396
13  District of Columbia     670868     668791     671803
14               Florida   21589602   21828069   22244823
15               Georgia   10729828   10788029   10912876
16                Hawaii    1451043    1447154    1440196
17                 Idaho    1849202    1904314    1939033
18              Illinois   12786580   12686469   12582032
19               Indiana    6788799    6813532    6833037
20                  Iowa    3190571    3197689    3200517
21                Kansas    2937919    2937922    2937150
22              Kentucky    4507445    4506589    4512310
23             Louisiana    4651664    4627098    4590241
24                 Maine    1363557    1377238    1385340
25              Maryland    6173205    6174610    6164660
26         Massachusetts    6995729    6989690    6981974
27              Michigan   10069577   10037504   10034113
28             Minnesota    5709852    5711471    5717184
29           Mississippi    2958141    2949586    2940057
30              Missouri    6153998    6169823    6177957
31               Montana    1087075    1106227    1122867
32              Nebraska    1962642    1963554    1967923
33                Nevada    3115648    3146402    3177772
34         New Hampshire    1378587    1387505    1395231
35            New Jersey    9271689    9267961    9261699
36            New Mexico    2118390    2116677    2113344
37              New York   20108296   19857492   19677151
38        North Carolina   10449445   10565885   10698973
39          North Dakota     779518     777934     779261
40                  Ohio   11797517   11764342   11756058
41              Oklahoma    3964912    3991225    4019800
42                Oregon    4244795    4256301    4240137
43          Pennsylvania   12994440   13012059   12972008
44          Rhode Island    1096345    1096985    1093734
45        South Carolina    5131848    5193266    5282634
46          South Dakota     887799     896164     909824
47             Tennessee    6925619    6968351    7051339
48                 Texas   29232474   29558864   30029572
49                  Utah    3283785    3339113    3380800
50               Vermont     642893     646972     647064
51              Virginia    8636471    8657365    8683619
52            Washington    7724031    7740745    7785786
53         West Virginia    1791420    1785526    1775156
54             Wisconsin    5896271    5880101    5892539
55               Wyoming     577605     579483     581381
57           Puerto Rico    3281557    3262693    3221789

<br/><br/>

---

# Join Data (Merge DataFrames)

Time to `merge`! Here I use the DataFrame method `df1.merge(right=df2, ...)` on DataFrame `df1` ([documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)). Contrast this with the function `pd.merge(left=df1, right=df2, ...)` ([documentation](https://pandas.pydata.org/docs/reference/api/pandas.merge.html?highlight=pandas%20merge#pandas.merge)). Feel free to use either.

In [18]:
# Show the three tables that we are going to join
display(tb_df.tail(2))
display(census_2010s_df.tail(2))
display(census_2020s_df.tail(2))

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
50,Wisconsin,51,35,66,0.88,0.59,1.12
51,Wyoming,1,0,3,0.17,0.00,0.52

,Geographic Area,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
55,Wyoming,564487,567299,576305,582122,582531,585613,584215,578931,577601,578759
57,Puerto Rico,3721525,3678732,3634488,3593077,3534874,3473232,3406672,3325286,3193354,3193694

   Geographic Area     2020     2021     2022
55         Wyoming   577605   579483   581381
57     Puerto Rico  3281557  3262693  3221789

In [19]:
# merge TB dataframe with two US census dataframes
tb_census_df = (
    tb_df
    .merge(right=census_2010s_df,
           left_on="U.S. jurisdiction", right_on="Geographic Area")
    .merge(right=census_2020s_df,
           left_on="U.S. jurisdiction", right_on="Geographic Area")
)
tb_census_df.tail()

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021,Geographic Area_x,2010,2011,...,2014,2015,2016,2017,2018,2019,Geographic Area_y,2020,2021,2022
46,Virginia,191,169,161,2.23,1.96,1.86,Virginia,8023699,8101155,...,8310993,8361808,8410106,8463587,8501286,8535519,Virginia,8636471,8657365,8683619
47,Washington,221,163,199,2.90,2.11,2.57,Washington,6742830,6826627,...,7054655,7163657,7294771,7423362,7523869,7614893,Washington,7724031,7740745,7785786
48,West Virginia,9,13,7,0.50,0.73,0.39,West Virginia,1854239,1856301,...,1849489,1842050,1831023,1817004,1804291,1792147,West Virginia,1791420,1785526,1775156
49,Wisconsin,51,35,66,0.88,0.59,1.12,Wisconsin,5690475,5705288,...,5751525,5760940,5772628,5790186,5807406,5822434,Wisconsin,5896271,5880101,5892539
50,Wyoming,1,0,3,0.17,0.00,0.52,Wyoming,564487,567299,...,582531,585613,584215,578931,577601,578759,Wyoming,577605,579483,581381

This is a little unwieldy. We could either drop the unneeded columns now, or just merge on smaller census DataFrames. Let's do the latter.

In [20]:
# try merging again, but cleaner this time
tb_census_df = (
    tb_df
    .merge(right=census_2010s_df[["Geographic Area", "2019"]],
           left_on="U.S. jurisdiction", right_on="Geographic Area")
    .drop(columns="Geographic Area")
    .merge(right=census_2020s_df[["Geographic Area", "2020", "2021"]],
           left_on="U.S. jurisdiction", right_on="Geographic Area")
    .drop(columns="Geographic Area")
)
tb_census_df.tail()

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021,2019,2020,2021
46,Virginia,191,169,161,2.23,1.96,1.86,8535519,8636471,8657365
47,Washington,221,163,199,2.90,2.11,2.57,7614893,7724031,7740745
48,West Virginia,9,13,7,0.50,0.73,0.39,1792147,1791420,1785526
49,Wisconsin,51,35,66,0.88,0.59,1.12,5822434,5896271,5880101
50,Wyoming,1,0,3,0.17,0.00,0.52,578759,577605,579483

## Reproduce incidence

Let's recompute incidence to make sure we know where the original CDC numbers came from.

From the [CDC report](https://www.cdc.gov/mmwr/volumes/71/wr/mm7112a1.htm?s_cid=mm7112a1_w#T1_down): TB incidence is computed as “Cases per 100,000 persons using mid-year population estimates from the U.S. Census Bureau.”

If we define a group as 100,000 people, then we can compute the TB incidence for a given state population as

$$\text{TB incidence} = \frac{\text{\# TB cases in population}}{\text{\# groups in population}} = \frac{\text{\# TB cases in population}}{\text{population}/100000} $$

$$= \frac{\text{\# TB cases in population}}{\text{population}} \times 100000$$

Let's try this for 2019:

In [21]:
tb_census_df["recompute incidence 2019"] = (
    tb_census_df["TB cases 2019"]/tb_census_df["2019"] * 100_000
)
tb_census_df

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021,2019,2020,2021,recompute incidence 2019
0,Alabama,87,72,92,1.77,1.43,1.83,4903185,5031362,5049846,1.774357
1,Alaska,58,58,58,7.91,7.92,7.92,731545,732923,734182,7.928425
2,Arizona,183,136,129,2.51,1.89,1.77,7278717,7179943,7264877,2.514179
3,Arkansas,64,59,69,2.12,1.96,2.28,3017804,3014195,3028122,2.120747
4,California,2111,1706,1750,5.35,4.32,4.46,39512223,39501653,39142991,5.342651
5,Colorado,66,52,58,1.15,0.90,1.00,5758736,5784865,5811297,1.146085
6,Connecticut,67,54,54,1.88,1.50,1.50,3565287,3597362,3623355,1.879232
7,Delaware,18,17,43,1.84,1.71,4.29,973764,992114,1004807,1.848497
8,District of Columbia,24,19,19,3.39,2.75,2.84,705749,670868,668791,3.400642
9,Florida,558,412,499,2.60,1.91,2.29,21477737,21589602,21828069,2.598039
10,Georgia,302,221,228,2.84,2.06,2.11,10617423,10729828,10788029,2.844381
11,Hawaii,99,92,106,6.99,6.34,7.35,1415872,1451043,1447154,6.992157
12,Idaho,7,8,4,0.39,0.43,0.21,1787065,1849202,1904314,0.391704
13,Illinois,326,216,255,2.57,1.69,2.01,12671821,12786580,12686469,2.572637
14,Indiana,108,92,127,1.60,1.36,1.87,6732219,6788799,6813532,1.604226
15,Iowa,52,39,49,1.65,1.22,1.53,3155070,3190571,3197689,1.648141
16,Kansas,37,37,43,1.27,1.26,1.47,2913314,2937919,2937922,1.270031
17,Kentucky,66,67,57,1.48,1.49,1.26,4467673,4507445,4506589,1.477279
18,Louisiana,88,99,86,1.89,2.13,1.86,4648794,4651664,4627098,1.892964
19,Maine,18,17,14,1.34,1.25,1.02,1344212,1363557,1377238,1.339074
20,Maryland,209,148,192,3.45,2.40,3.11,6045680,6173205,6174610,3.457014
21,Massachusetts,178,142,151,2.58,2.02,2.16,6892503,6995729,6989690,2.582516
22,Michigan,131,101,136,1.31,1.00,1.35,9986857,10069577,10037504,1.311724
23,Minnesota,148,117,134,2.62,2.05,2.35,5639632,5709852,5711471,2.624285
24,Mississippi,58,41,45,1.95,1.39,1.53,2976149,2958141,2949586,1.948827
25,Missouri,70,79,77,1.14,1.28,1.25,6137428,6153998,6169823,1.140543
26,Montana,2,4,3,0.19,0.37,0.27,1068778,1087075,1106227,0.18713
27,Nebraska,17,33,22,0.88,1.68,1.12,1934408,1962642,1963554,0.878822
28,Nevada,53,57,61,1.71,1.83,1.94,3080156,3115648,3146402,1.720692
29,New Hampshire,6,12,12,0.44,0.87,0.86,1359711,1378587,1387505,0.44127
30,New Jersey,310,245,279,3.49,2.64,3.01,8882190,9271689,9267961,3.49013
31,New Mexico,41,29,24,1.95,1.37,1.13,2096829,2118390,2116677,1.955334
32,New York,746,605,681,3.83,3.00,3.43,19453561,20108296,19857492,3.834773
33,North Carolina,185,159,178,1.76,1.52,1.69,10488084,10449445,10565885,1.763907
34,North Dakota,18,10,15,2.36,1.28,1.94,762062,779518,777934,2.362013
35,Ohio,150,130,149,1.28,1.10,1.26,11689100,11797517,11764342,1.283247
36,Oklahoma,73,67,69,1.84,1.69,1.73,3956971,3964912,3991225,1.844845
37,Oregon,70,67,78,1.66,1.58,1.84,4217737,4244795,4256301,1.659658
38,Pennsylvania,199,156,166,1.55,1.20,1.28,12801989,12994440,13012059,1.554446
39,Rhode Island,14,7,17,1.32,0.64,1.55,1059361,1096345,1096985,1.321551
40,South Carolina,80,67,88,1.55,1.31,1.70,5148714,5131848,5193266,1.553786
41,South Dakota,16,16,12,1.80,1.80,1.34,884659,887799,896164,1.808606
42,Tennessee,129,113,85,1.89,1.63,1.22,6829174,6925619,6968351,1.888955
43,Texas,1154,883,991,3.98,3.02,3.36,28995881,29232474,29558864,3.979876
44,Utah,27,29,17,0.84,0.88,0.51,3205958,3283785,3339113,0.842182
45,Vermont,4,3,2,0.64,0.47,0.31,623989,642893,646972,0.641037
46,Virginia,191,169,161,2.23,1.96,1.86,8535519,8636471,8657365,2.237708
47,Washington,221,163,199,2.90,2.11,2.57,7614893,7724031,7740745,2.902208
48,West Virginia,9,13,7,0.50,0.73,0.39,1792147,1791420,1785526,0.502191
49,Wisconsin,51,35,66,0.88,0.59,1.12,5822434,5896271,5880101,0.875922
50,Wyoming,1,0,3,0.17,0.00,0.52,578759,577605,579483,0.172783

Awesome!!!

Let's use a for-loop and Python format strings to compute TB incidence for all years. Python f-strings are just used for the purposes of this demo, but they're handy to know when you explore data beyond this course ([Python documentation](https://docs.python.org/3/tutorial/inputoutput.html)).

In [22]:
# recompute incidence for all years
for year in [2019, 2020, 2021]:
    tb_census_df[f"recompute incidence {year}"] = (
        tb_census_df[f"TB cases {year}"]/tb_census_df[f"{year}"]*100_000
    )
tb_census_df

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021,2019,2020,2021,recompute incidence 2019,recompute incidence 2020,recompute incidence 2021
0,Alabama,87,72,92,1.77,1.43,1.83,4903185,5031362,5049846,1.774357,1.431024,1.821838
1,Alaska,58,58,58,7.91,7.92,7.92,731545,732923,734182,7.928425,7.913519,7.899949
2,Arizona,183,136,129,2.51,1.89,1.77,7278717,7179943,7264877,2.514179,1.894165,1.775667
3,Arkansas,64,59,69,2.12,1.96,2.28,3017804,3014195,3028122,2.120747,1.957405,2.27864
4,California,2111,1706,1750,5.35,4.32,4.46,39512223,39501653,39142991,5.342651,4.318807,4.470788
5,Colorado,66,52,58,1.15,0.90,1.00,5758736,5784865,5811297,1.146085,0.898897,0.998056
6,Connecticut,67,54,54,1.88,1.50,1.50,3565287,3597362,3623355,1.879232,1.5011,1.490331
7,Delaware,18,17,43,1.84,1.71,4.29,973764,992114,1004807,1.848497,1.713513,4.279429
8,District of Columbia,24,19,19,3.39,2.75,2.84,705749,670868,668791,3.400642,2.832152,2.840947
9,Florida,558,412,499,2.60,1.91,2.29,21477737,21589602,21828069,2.598039,1.908326,2.286047
10,Georgia,302,221,228,2.84,2.06,2.11,10617423,10729828,10788029,2.844381,2.059679,2.113454
11,Hawaii,99,92,106,6.99,6.34,7.35,1415872,1451043,1447154,6.992157,6.340267,7.324721
12,Idaho,7,8,4,0.39,0.43,0.21,1787065,1849202,1904314,0.391704,0.432619,0.210049
13,Illinois,326,216,255,2.57,1.69,2.01,12671821,12786580,12686469,2.572637,1.689271,2.010016
14,Indiana,108,92,127,1.60,1.36,1.87,6732219,6788799,6813532,1.604226,1.355173,1.863938
15,Iowa,52,39,49,1.65,1.22,1.53,3155070,3190571,3197689,1.648141,1.222352,1.532357
16,Kansas,37,37,43,1.27,1.26,1.47,2913314,2937919,2937922,1.270031,1.259395,1.46362
17,Kentucky,66,67,57,1.48,1.49,1.26,4467673,4507445,4506589,1.477279,1.48643,1.264815
18,Louisiana,88,99,86,1.89,2.13,1.86,4648794,4651664,4627098,1.892964,2.128271,1.858616
19,Maine,18,17,14,1.34,1.25,1.02,1344212,1363557,1377238,1.339074,1.246739,1.016527
20,Maryland,209,148,192,3.45,2.40,3.11,6045680,6173205,6174610,3.457014,2.397458,3.109508
21,Massachusetts,178,142,151,2.58,2.02,2.16,6892503,6995729,6989690,2.582516,2.02981,2.160325
22,Michigan,131,101,136,1.31,1.00,1.35,9986857,10069577,10037504,1.311724,1.003021,1.354919
23,Minnesota,148,117,134,2.62,2.05,2.35,5639632,5709852,5711471,2.624285,2.04909,2.346156
24,Mississippi,58,41,45,1.95,1.39,1.53,2976149,2958141,2949586,1.948827,1.386006,1.525638
25,Missouri,70,79,77,1.14,1.28,1.25,6137428,6153998,6169823,1.140543,1.283718,1.24801
26,Montana,2,4,3,0.19,0.37,0.27,1068778,1087075,1106227,0.18713,0.36796,0.271192
27,Nebraska,17,33,22,0.88,1.68,1.12,1934408,1962642,1963554,0.878822,1.681407,1.120417
28,Nevada,53,57,61,1.71,1.83,1.94,3080156,3115648,3146402,1.720692,1.829475,1.938722
29,New Hampshire,6,12,12,0.44,0.87,0.86,1359711,1378587,1387505,0.44127,0.870456,0.864862
30,New Jersey,310,245,279,3.49,2.64,3.01,8882190,9271689,9267961,3.49013,2.642453,3.010371
31,New Mexico,41,29,24,1.95,1.37,1.13,2096829,2118390,2116677,1.955334,1.368964,1.133853
32,New York,746,605,681,3.83,3.00,3.43,19453561,20108296,19857492,3.834773,3.008708,3.429436
33,North Carolina,185,159,178,1.76,1.52,1.69,10488084,10449445,10565885,1.763907,1.521612,1.684667
34,North Dakota,18,10,15,2.36,1.28,1.94,762062,779518,777934,2.362013,1.282844,1.928184
35,Ohio,150,130,149,1.28,1.10,1.26,11689100,11797517,11764342,1.283247,1.101927,1.266539
36,Oklahoma,73,67,69,1.84,1.69,1.73,3956971,3964912,3991225,1.844845,1.689823,1.728793
37,Oregon,70,67,78,1.66,1.58,1.84,4217737,4244795,4256301,1.659658,1.578404,1.832577
38,Pennsylvania,199,156,166,1.55,1.20,1.28,12801989,12994440,13012059,1.554446,1.200513,1.27574
39,Rhode Island,14,7,17,1.32,0.64,1.55,1059361,1096345,1096985,1.321551,0.638485,1.549702
40,South Carolina,80,67,88,1.55,1.31,1.70,5148714,5131848,5193266,1.553786,1.305573,1.694502
41,South Dakota,16,16,12,1.80,1.80,1.34,884659,887799,896164,1.808606,1.80221,1.339041
42,Tennessee,129,113,85,1.89,1.63,1.22,6829174,6925619,6968351,1.888955,1.631623,1.219801
43,Texas,1154,883,991,3.98,3.02,3.36,28995881,29232474,29558864,3.979876,3.020613,3.352632
44,Utah,27,29,17,0.84,0.88,0.51,3205958,3283785,3339113,0.842182,0.883127,0.509117
45,Vermont,4,3,2,0.64,0.47,0.31,623989,642893,646972,0.641037,0.466641,0.309132
46,Virginia,191,169,161,2.23,1.96,1.86,8535519,8636471,8657365,2.237708,1.956818,1.859688
47,Washington,221,163,199,2.90,2.11,2.57,7614893,7724031,7740745,2.902208,2.110297,2.570812
48,West Virginia,9,13,7,0.50,0.73,0.39,1792147,1791420,1785526,0.502191,0.725681,0.392041
49,Wisconsin,51,35,66,0.88,0.59,1.12,5822434,5896271,5880101,0.875922,0.593596,1.12243
50,Wyoming,1,0,3,0.17,0.00,0.52,578759,577605,579483,0.172783,0.0,0.517703

These numbers look pretty close!!! There are a few errors in the hundredths place, particularly in 2021. It may be useful to further explore reasons behind this discrepancy. We'll leave it to you!

In [23]:
tb_census_df.describe()

,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021,2019,2020,2021,recompute incidence 2019,recompute incidence 2020,recompute incidence 2021
count,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.0,51.0,51.0,51.0,51.0,51.0
mean,174.509804,140.647059,154.117647,2.102549,1.782941,1.971961,6436069.078431,6500225.72549,6510422.627451,2.104969,1.784655,1.969928
std,341.738752,271.055775,286.781007,1.498745,1.337414,1.478468,7360660.467814,7408168.462614,7394300.076705,1.500236,1.338263,1.474929
min,1.000000,0.000000,2.000000,0.170000,0.000000,0.210000,578759.0,577605.0,579483.0,0.172783,0.0,0.210049
25%,25.500000,29.000000,23.000000,1.295000,1.210000,1.235000,1789606.0,1820311.0,1844920.0,1.297485,1.211433,1.233905
50%,70.000000,67.000000,69.000000,1.800000,1.520000,1.700000,4467673.0,4507445.0,4506589.0,1.808606,1.521612,1.694502
75%,180.500000,139.000000,150.000000,2.575000,1.990000,2.220000,7446805.0,7451987.0,7502811.0,2.577577,1.993607,2.219482
max,2111.000000,1706.000000,1750.000000,7.910000,7.920000,7.920000,39512223.0,39501653.0,39142991.0,7.928425,7.913519,7.899949


<br><br><br>

---

# Bonus EDA

**How do we reproduce that reported statistic in the original [CDC report](https://www.cdc.gov/mmwr/volumes/71/wr/mm7112a1.htm?s_cid=mm7112a1_w)?**

> Reported TB incidence (cases per 100,000 persons) increased **9.4%**, from **2.2** during 2020 to **2.4** during 2021 but was lower than incidence during 2019 (2.7). Increases occurred among both U.S.-born and non–U.S.-born persons.

This is TB incidence computed across the entire U.S. population! How do we reproduce this
* We need to reproduce the "Total" TB incidences in our rolled record.
* But our current `tb_census_df` only has 51 entries (50 states plus Washington, D.C.). There is no rolled record.
* What happened...?

Let's get exploring!
<br/><br/>

Before we keep exploring, I'm going to set all indexes to more meaningful values, instead of just numbers that pertained to some row at some point. This will make our cleaning slightly easier.

In [24]:
tb_df = tb_df.set_index("U.S. jurisdiction")
tb_df

,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
U.S. jurisdiction,,,,,,
Total,8900,7173,7860,2.71,2.16,2.37
Alabama,87,72,92,1.77,1.43,1.83
Alaska,58,58,58,7.91,7.92,7.92
Arizona,183,136,129,2.51,1.89,1.77
Arkansas,64,59,69,2.12,1.96,2.28
California,2111,1706,1750,5.35,4.32,4.46
Colorado,66,52,58,1.15,0.90,1.00
Connecticut,67,54,54,1.88,1.50,1.50
Delaware,18,17,43,1.84,1.71,4.29
District of Columbia,24,19,19,3.39,2.75,2.84
Florida,558,412,499,2.60,1.91,2.29
Georgia,302,221,228,2.84,2.06,2.11
Hawaii,99,92,106,6.99,6.34,7.35
Idaho,7,8,4,0.39,0.43,0.21
Illinois,326,216,255,2.57,1.69,2.01
Indiana,108,92,127,1.60,1.36,1.87
Iowa,52,39,49,1.65,1.22,1.53
Kansas,37,37,43,1.27,1.26,1.47
Kentucky,66,67,57,1.48,1.49,1.26
Louisiana,88,99,86,1.89,2.13,1.86
Maine,18,17,14,1.34,1.25,1.02
Maryland,209,148,192,3.45,2.40,3.11
Massachusetts,178,142,151,2.58,2.02,2.16
Michigan,131,101,136,1.31,1.00,1.35
Minnesota,148,117,134,2.62,2.05,2.35
Mississippi,58,41,45,1.95,1.39,1.53
Missouri,70,79,77,1.14,1.28,1.25
Montana,2,4,3,0.19,0.37,0.27
Nebraska,17,33,22,0.88,1.68,1.12
Nevada,53,57,61,1.71,1.83,1.94
New Hampshire,6,12,12,0.44,0.87,0.86
New Jersey,310,245,279,3.49,2.64,3.01
New Mexico,41,29,24,1.95,1.37,1.13
New York,746,605,681,3.83,3.00,3.43
North Carolina,185,159,178,1.76,1.52,1.69
North Dakota,18,10,15,2.36,1.28,1.94
Ohio,150,130,149,1.28,1.10,1.26
Oklahoma,73,67,69,1.84,1.69,1.73
Oregon,70,67,78,1.66,1.58,1.84
Pennsylvania,199,156,166,1.55,1.20,1.28
Rhode Island,14,7,17,1.32,0.64,1.55
South Carolina,80,67,88,1.55,1.31,1.70
South Dakota,16,16,12,1.80,1.80,1.34
Tennessee,129,113,85,1.89,1.63,1.22
Texas,1154,883,991,3.98,3.02,3.36
Utah,27,29,17,0.84,0.88,0.51
Vermont,4,3,2,0.64,0.47,0.31
Virginia,191,169,161,2.23,1.96,1.86
Washington,221,163,199,2.90,2.11,2.57
West Virginia,9,13,7,0.50,0.73,0.39
Wisconsin,51,35,66,0.88,0.59,1.12
Wyoming,1,0,3,0.17,0.00,0.52

In [ ]:
census_2010s_df = census_2010s_df.set_index("Geographic Area")
census_2010s_df

In [25]:
census_2020s_df = census_2020s_df.set_index("Geographic Area")
census_2020s_df

                           2020       2021       2022
Geographic Area
United States         331511512  332031554  333287557
Northeast              57448898   57259257   57040406
Midwest                68961043   68836505   68787595
South                 126450613  127346029  128716192
West                   78650958   78589763   78743364
Alabama                 5031362    5049846    5074296
Alaska                   732923     734182     733583
Arizona                 7179943    7264877    7359197
Arkansas                3014195    3028122    3045637
California             39501653   39142991   39029342
Colorado                5784865    5811297    5839926
Connecticut             3597362    3623355    3626205
Delaware                 992114    1004807    1018396
District of Columbia     670868     668791     671803
Florida                21589602   21828069   22244823
Georgia                10729828   10788029   10912876
Hawaii                  1451043    1447154    1440196
Idaho                   1849202    1904314    1939033
Illinois               12786580   12686469   12582032
Indiana                 6788799    6813532    6833037
Iowa                    3190571    3197689    3200517
Kansas                  2937919    2937922    2937150
Kentucky                4507445    4506589    4512310
Louisiana               4651664    4627098    4590241
Maine                   1363557    1377238    1385340
Maryland                6173205    6174610    6164660
Massachusetts           6995729    6989690    6981974
Michigan               10069577   10037504   10034113
Minnesota               5709852    5711471    5717184
Mississippi             2958141    2949586    2940057
Missouri                6153998    6169823    6177957
Montana                 1087075    1106227    1122867
Nebraska                1962642    1963554    1967923
Nevada                  3115648    3146402    3177772
New Hampshire           1378587    1387505    1395231
New Jersey              9271689    9267961    9261699
New Mexico              2118390    2116677    2113344
New York               20108296   19857492   19677151
North Carolina         10449445   10565885   10698973
North Dakota             779518     777934     779261
Ohio                   11797517   11764342   11756058
Oklahoma                3964912    3991225    4019800
Oregon                  4244795    4256301    4240137
Pennsylvania           12994440   13012059   12972008
Rhode Island            1096345    1096985    1093734
South Carolina          5131848    5193266    5282634
South Dakota             887799     896164     909824
Tennessee               6925619    6968351    7051339
Texas                  29232474   29558864   30029572
Utah                    3283785    3339113    3380800
Vermont                  642893     646972     647064
Virginia                8636471    8657365    8683619
Washington              7724031    7740745    7785786
West Virginia           1791420    1785526    1775156
Wisconsin               5896271    5880101    5892539
Wyoming                  577605     579483     581381
Puerto Rico             3281557    3262693    3221789

It turns out that our merge above only kept state records, even though our original `tb_df` had the "Total" rolled record:

In [26]:
tb_df.head()

,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
U.S. jurisdiction,,,,,,
Total,8900,7173,7860,2.71,2.16,2.37
Alabama,87,72,92,1.77,1.43,1.83
Alaska,58,58,58,7.91,7.92,7.92
Arizona,183,136,129,2.51,1.89,1.77
Arkansas,64,59,69,2.12,1.96,2.28

Recall that merge by default does an **inner** merge by default, meaning that it only preserves keys that are present in **both** DataFrames.

The rolled records in our census dataframes have different `Geographic Area` fields, which was the key we merged on:

In [27]:
census_2010s_df

,Geographic Area,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,United States,309321666,311556874,313830990,315993715,318301008,320635163,322941311,324985539,326687501,328239523
1,Northeast,55380134,55604223,55775216,55901806,56006011,56034684,56042330,56059240,56046620,55982803
2,Midwest,66974416,67157800,67336743,67560379,67745167,67860583,67987540,68126781,68236628,68329004
3,South,114866680,116006522,117241208,118364400,119624037,120997341,122351760,123542189,124569433,125580448
4,West,72100436,72788329,73477823,74167130,74925793,75742555,76559681,77257329,77834820,78347268
5,Alabama,4785437,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185
6,Alaska,713910,722128,730443,737068,736283,737498,741456,739700,735139,731545
7,Arizona,6407172,6472643,6554978,6632764,6730413,6829676,6941072,7044008,7158024,7278717
8,Arkansas,2921964,2940667,2952164,2959400,2967392,2978048,2989918,3001345,3009733,3017804
9,California,37319502,37638369,37948800,38260787,38596972,38918045,39167117,39358497,39461588,39512223
10,Colorado,5047349,5121108,5192647,5269035,5350101,5450623,5539215,5611885,5691287,5758736
11,Connecticut,3579114,3588283,3594547,3594841,3594524,3587122,3578141,3573297,3571520,3565287
12,Delaware,899593,907381,915179,923576,932487,941252,948921,956823,965479,973764
13,District of Columbia,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
14,Florida,18845537,19053237,19297822,19545621,19845911,20209042,20613477,20963613,21244317,21477737
15,Georgia,9711881,9802431,9901430,9972479,10067278,10178447,10301890,10410330,10511131,10617423
16,Hawaii,1363963,1379329,1394804,1408243,1414538,1422052,1427559,1424393,1420593,1415872
17,Idaho,1570746,1583910,1595324,1611206,1631112,1651059,1682380,1717715,1750536,1787065
18,Illinois,12840503,12867454,12882510,12895129,12884493,12858913,12820527,12778828,12723071,12671821
19,Indiana,6490432,6516528,6537703,6568713,6593644,6608422,6634304,6658078,6695497,6732219
20,Iowa,3050745,3066336,3076190,3092997,3109350,3120960,3131371,3141550,3148618,3155070
21,Kansas,2858190,2869225,2885257,2893212,2900475,2909011,2910844,2908718,2911359,2913314
22,Kentucky,4348181,4369821,4386346,4404659,4414349,4425976,4438182,4452268,4461153,4467673
23,Louisiana,4544532,4575625,4600972,4624527,4644013,4664628,4678135,4670560,4659690,4648794
24,Maine,1327629,1328284,1327729,1328009,1330513,1328262,1331317,1334612,1339057,1344212
25,Maryland,5788645,5839419,5886992,5923188,5957283,5985562,6003323,6023868,6035802,6045680
26,Massachusetts,6566307,6613583,6663005,6713315,6762596,6794228,6823608,6859789,6882635,6892503
27,Michigan,9877510,9882412,9897145,9913065,9929848,9931715,9950571,9973114,9984072,9986857
28,Minnesota,5310828,5346143,5376643,5413479,5451079,5482032,5522744,5566230,5606249,5639632
29,Mississippi,2970548,2978731,2983816,2988711,2990468,2988471,2987938,2988510,2981020,2976149
30,Missouri,5995974,6010275,6024367,6040715,6056202,6071732,6087135,6106670,6121623,6137428
31,Montana,990697,997316,1003783,1013569,1021869,1030475,1040859,1052482,1060665,1068778
32,Nebraska,1829542,1840672,1853303,1865279,1879321,1891277,1905616,1915947,1925614,1934408
33,Nevada,2702405,2712730,2743996,2775970,2817628,2866939,2917563,2969905,3027341,3080156
34,New Hampshire,1316762,1320202,1324232,1326622,1333341,1336350,1342307,1348787,1353465,1359711
35,New Jersey,8799446,8828117,8844942,8856972,8864525,8867949,8870827,8885525,8886025,8882190
36,New Mexico,2064552,2080450,2087309,2092273,2089568,2089291,2091630,2091784,2092741,2096829
37,New York,19399878,19499241,19572932,19624447,19651049,19654666,19633428,19589572,19530351,19453561
38,North Carolina,9574323,9657592,9749476,9843336,9932887,10031646,10154788,10268233,10381615,10488084
39,North Dakota,674715,685225,701176,722036,737401,754066,754434,754942,758080,762062
40,Ohio,11539336,11544663,11548923,11576684,11602700,11617527,11634370,11659650,11676341,11689100
41,Oklahoma,3759944,3788379,3818814,3853214,3878187,3909500,3926331,3931316,3940235,3956971
42,Oregon,3837491,3872036,3899001,3922468,3963244,4015792,4089976,4143625,4181886,4217737
43,Pennsylvania,12711160,12745815,12767118,12776309,12788313,12784826,12782275,12787641,12800922,12801989
44,Rhode Island,1053959,1053649,1054621,1055081,1055936,1056065,1056770,1055673,1058287,1059361
45,South Carolina,4635649,4671994,4717354,4764080,4823617,4891938,4957968,5021268,5084156,5148714
46,South Dakota,816166,823579,833566,842316,849129,853988,862996,872868,878698,884659
47,Tennessee,6355311,6399291,6453898,6494340,6541223,6591170,6646010,6708799,6771631,6829174
48,Texas,25241971,25645629,26084481,26480266,26964333,27470056,27914410,28295273,28628666,28995881
49,Utah,2775332,2814384,2853375,2897640,2936879,2981835,3041868,3101042,3153550,3205958
50,Vermont,625879,627049,626090,626210,625214,625216,623657,624344,624358,623989
51,Virginia,8023699,8101155,8185080,8252427,8310993,8361808,8410106,8463587,8501286,8535519
52,Washington,6742830,6826627,6897058,6963985,7054655,7163657,7294771,7423362,7523869,7614893
53,West Virginia,1854239,1856301,1856872,1853914,1849489,1842050,1831023,1817004,1804291,1792147
54,Wisconsin,5690475,5705288,5719960,5736754,5751525,5760940,5772628,5790186,5807406,5822434
55,Wyoming,564487,567299,576305,582122,582531,585613,584215,578931,577601,578759
57,Puerto Rico,3721525,3678732,3634488,3593077,3534874,3473232,3406672,3325286,3193354,3193694

The Census DataFrame has several rolled records. The aggregate record we are looking for actually has the Geographic Area named "United States".

One straightforward way to get the right merge is to rename the value itself. Because we now have the Geographic Area index, we'll use `df.rename()` ([documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html)):

In [28]:
# rename rolled record for 2010s
census_2010s_df.rename(index={'United States':'Total'}, inplace=True)
census_2010s_df

,Geographic Area,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,United States,309321666,311556874,313830990,315993715,318301008,320635163,322941311,324985539,326687501,328239523
1,Northeast,55380134,55604223,55775216,55901806,56006011,56034684,56042330,56059240,56046620,55982803
2,Midwest,66974416,67157800,67336743,67560379,67745167,67860583,67987540,68126781,68236628,68329004
3,South,114866680,116006522,117241208,118364400,119624037,120997341,122351760,123542189,124569433,125580448
4,West,72100436,72788329,73477823,74167130,74925793,75742555,76559681,77257329,77834820,78347268
5,Alabama,4785437,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185
6,Alaska,713910,722128,730443,737068,736283,737498,741456,739700,735139,731545
7,Arizona,6407172,6472643,6554978,6632764,6730413,6829676,6941072,7044008,7158024,7278717
8,Arkansas,2921964,2940667,2952164,2959400,2967392,2978048,2989918,3001345,3009733,3017804
9,California,37319502,37638369,37948800,38260787,38596972,38918045,39167117,39358497,39461588,39512223
10,Colorado,5047349,5121108,5192647,5269035,5350101,5450623,5539215,5611885,5691287,5758736
11,Connecticut,3579114,3588283,3594547,3594841,3594524,3587122,3578141,3573297,3571520,3565287
12,Delaware,899593,907381,915179,923576,932487,941252,948921,956823,965479,973764
13,District of Columbia,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
14,Florida,18845537,19053237,19297822,19545621,19845911,20209042,20613477,20963613,21244317,21477737
15,Georgia,9711881,9802431,9901430,9972479,10067278,10178447,10301890,10410330,10511131,10617423
16,Hawaii,1363963,1379329,1394804,1408243,1414538,1422052,1427559,1424393,1420593,1415872
17,Idaho,1570746,1583910,1595324,1611206,1631112,1651059,1682380,1717715,1750536,1787065
18,Illinois,12840503,12867454,12882510,12895129,12884493,12858913,12820527,12778828,12723071,12671821
19,Indiana,6490432,6516528,6537703,6568713,6593644,6608422,6634304,6658078,6695497,6732219
20,Iowa,3050745,3066336,3076190,3092997,3109350,3120960,3131371,3141550,3148618,3155070
21,Kansas,2858190,2869225,2885257,2893212,2900475,2909011,2910844,2908718,2911359,2913314
22,Kentucky,4348181,4369821,4386346,4404659,4414349,4425976,4438182,4452268,4461153,4467673
23,Louisiana,4544532,4575625,4600972,4624527,4644013,4664628,4678135,4670560,4659690,4648794
24,Maine,1327629,1328284,1327729,1328009,1330513,1328262,1331317,1334612,1339057,1344212
25,Maryland,5788645,5839419,5886992,5923188,5957283,5985562,6003323,6023868,6035802,6045680
26,Massachusetts,6566307,6613583,6663005,6713315,6762596,6794228,6823608,6859789,6882635,6892503
27,Michigan,9877510,9882412,9897145,9913065,9929848,9931715,9950571,9973114,9984072,9986857
28,Minnesota,5310828,5346143,5376643,5413479,5451079,5482032,5522744,5566230,5606249,5639632
29,Mississippi,2970548,2978731,2983816,2988711,2990468,2988471,2987938,2988510,2981020,2976149
30,Missouri,5995974,6010275,6024367,6040715,6056202,6071732,6087135,6106670,6121623,6137428
31,Montana,990697,997316,1003783,1013569,1021869,1030475,1040859,1052482,1060665,1068778
32,Nebraska,1829542,1840672,1853303,1865279,1879321,1891277,1905616,1915947,1925614,1934408
33,Nevada,2702405,2712730,2743996,2775970,2817628,2866939,2917563,2969905,3027341,3080156
34,New Hampshire,1316762,1320202,1324232,1326622,1333341,1336350,1342307,1348787,1353465,1359711
35,New Jersey,8799446,8828117,8844942,8856972,8864525,8867949,8870827,8885525,8886025,8882190
36,New Mexico,2064552,2080450,2087309,2092273,2089568,2089291,2091630,2091784,2092741,2096829
37,New York,19399878,19499241,19572932,19624447,19651049,19654666,19633428,19589572,19530351,19453561
38,North Carolina,9574323,9657592,9749476,9843336,9932887,10031646,10154788,10268233,10381615,10488084
39,North Dakota,674715,685225,701176,722036,737401,754066,754434,754942,758080,762062
40,Ohio,11539336,11544663,11548923,11576684,11602700,11617527,11634370,11659650,11676341,11689100
41,Oklahoma,3759944,3788379,3818814,3853214,3878187,3909500,3926331,3931316,3940235,3956971
42,Oregon,3837491,3872036,3899001,3922468,3963244,4015792,4089976,4143625,4181886,4217737
43,Pennsylvania,12711160,12745815,12767118,12776309,12788313,12784826,12782275,12787641,12800922,12801989
44,Rhode Island,1053959,1053649,1054621,1055081,1055936,1056065,1056770,1055673,1058287,1059361
45,South Carolina,4635649,4671994,4717354,4764080,4823617,4891938,4957968,5021268,5084156,5148714
46,South Dakota,816166,823579,833566,842316,849129,853988,862996,872868,878698,884659
47,Tennessee,6355311,6399291,6453898,6494340,6541223,6591170,6646010,6708799,6771631,6829174
48,Texas,25241971,25645629,26084481,26480266,26964333,27470056,27914410,28295273,28628666,28995881
49,Utah,2775332,2814384,2853375,2897640,2936879,2981835,3041868,3101042,3153550,3205958
50,Vermont,625879,627049,626090,626210,625214,625216,623657,624344,624358,623989
51,Virginia,8023699,8101155,8185080,8252427,8310993,8361808,8410106,8463587,8501286,8535519
52,Washington,6742830,6826627,6897058,6963985,7054655,7163657,7294771,7423362,7523869,7614893
53,West Virginia,1854239,1856301,1856872,1853914,1849489,1842050,1831023,1817004,1804291,1792147
54,Wisconsin,5690475,5705288,5719960,5736754,5751525,5760940,5772628,5790186,5807406,5822434
55,Wyoming,564487,567299,576305,582122,582531,585613,584215,578931,577601,578759
57,Puerto Rico,3721525,3678732,3634488,3593077,3534874,3473232,3406672,3325286,3193354,3193694

In [ ]:
# same, but for 2020s rename rolled record
census_2020s_df.rename(index={'United States':'Total'}, inplace=True)
census_2020s_df

<br/>

Next let's rerun our merge. Note the different chaining, because we are now merging on indexes (`df.merge()` [documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)).

In [29]:
tb_census_df = (
    tb_df
    .merge(right=census_2010s_df[["2019"]],
           left_index=True, right_index=True)
    .merge(right=census_2020s_df[["2020", "2021"]],
           left_index=True, right_index=True)
)
tb_census_df

Empty DataFrame
Columns: [TB cases 2019, TB cases 2020, TB cases 2021, TB incidence 2019, TB incidence 2020, TB incidence 2021, 2019, 2020, 2021]
Index: []

<br/>

Finally, let's recompute our incidences:

In [39]:
# recompute incidence for all years
for year in [2019, 2020, 2021]:
    tb_census_df[f"recompute incidence {year}"] = tb_census_df[f"TB cases {year}"]/tb_census_df[f"{year}"]*100000
tb_census_df

Empty DataFrame
Columns: [TB cases 2019, TB cases 2020, TB cases 2021, TB incidence 2019, TB incidence 2020, TB incidence 2021, 2019, 2020, 2021, recompute incidence 2019, recompute incidence 2020, recompute incidence 2021]
Index: []

We reproduced the total U.S. incidences correctly!

We're almost there. Let's revisit the quote:

> Reported TB incidence (cases per 100,000 persons) increased **9.4%**, from **2.2** during 2020 to **2.4** during 2021 but was lower than incidence during 2019 (2.7). Increases occurred among both U.S.-born and non–U.S.-born persons.

Recall that percent change from $A$ to $B$ is computed as
$$\text{percent change} = \frac{B - A}{A} \times 100$$.

In [35]:
tb_census_df

Empty DataFrame
Columns: [TB cases 2019, TB cases 2020, TB cases 2021, TB incidence 2019, TB incidence 2020, TB incidence 2021, 2019, 2020, 2021, recompute incidence 2019, recompute incidence 2020, recompute incidence 2021]
Index: []

In [43]:
# incidence_2020 = tb_census_df.loc[:, ['Total', 'recompute incidence 2020']]
incidence_2020 = tb_census_df.iloc[:, [7, 10]]
incidence_2020

Empty DataFrame
Columns: [2020, recompute incidence 2020]
Index: []

In [44]:
# incidence_2021 = tb_census_df.loc['Total', 'recompute incidence 2021']
incidence_2021 = tb_census_df.iloc[:, [8, 11]]
incidence_2021

Empty DataFrame
Columns: [2021, recompute incidence 2021]
Index: []

In [45]:
difference = (incidence_2021 - incidence_2020)/incidence_2020 * 100
difference

Empty DataFrame
Columns: [2020, 2021, recompute incidence 2020, recompute incidence 2021]
Index: []

We did it!!!